#!/bin/sh
# Print SCSI Enclosure Services (SES) info. The output is dependent on the name
# of the script/symlink used to call it.
#
# ses:		Show all stats
# enc:		Show enclosure "w:x:y:z" value
# slot:		Show slot number as reported by the enclosure
# encdev:	Show the /dev/sg* device for the enclosure associated with
#		the vdev's slot.  This is useful for looking up the enclosure
#		device to pass to sg_ses.
# fault_led:	Show the value of the enclosure fault LED
# locate_led:	Show the value of the enclosure locate LED

script=$(basename $0)
if [ "$script" == "ses" ] ; then
	scripts='enc encdev slot fault_led locate_led'
else
	scripts="$script"
fi

for i in $scripts ; do
	if [ -z "$VDEV_ENC_SYSFS_PATH" ] ; then
		echo "$i="
		continue
	fi

	val=""
	case $i in
	enc)
		val=$(ls "$VDEV_ENC_SYSFS_PATH/../../" 2>/dev/null)
		;;
	slot)
		val=$(cat "$VDEV_ENC_SYSFS_PATH/slot" 2>/dev/null)
		;;
	encdev)
		val=$(ls "$VDEV_ENC_SYSFS_PATH/../device/scsi_generic" 2>/dev/null)
		;;
	fault_led)
		val=$(cat "$VDEV_ENC_SYSFS_PATH/fault" 2>/dev/null)
		;;
	locate_led)
		val=$(cat "$VDEV_ENC_SYSFS_PATH/locate" 2>/dev/null)
		;;
	esac
	echo "$i=$val"
done

